/**
 * A10 — writeSymbolsOut / getSymbolsData.
 *
 * Verifies that the --symbolsout skeleton file:
 *   • omits nameless addresses
 *   • omits auto-generated prose
 *   • emits structured-field placeholders for subroutines only
 *   • emits plain address+name lines for data and jump-target labels
 *   • sorts entries by address
 */

import assert = require('assert');
import { readFileSync, mkdtempSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { Disassembler } from '../disassembler/disasm';
import { writeSymbolsOut, SymbolEntry } from '../disassembler/argsWriter';


/** Binary: two subroutines + a data byte accessed by the first. */
const BINARY = new Uint8Array([
    0xCD, 0x10, 0x00,   // 0x0000: CALL 0x0010
    0xC9,               // 0x0003: RET
    0x76, 0x76, 0x76, 0x76,
    0x76, 0x76, 0x76, 0x76,
    0x76, 0x76, 0x76, 0x76,
    0x3E, 0x01,         // 0x0010: LD A,1
    0xC9,               // 0x0012: RET
]);

function makeDasm(): any {
    const dasm = new Disassembler() as any;
    dasm.labelSubPrefix      = 'SUB';
    dasm.labelLblPrefix      = 'LBL';
    dasm.labelDataLblPrefix  = 'DATA';
    dasm.labelLocalLabelPrefix = '_l';
    dasm.labelLoopPrefix     = '_loop';
    dasm.labelSelfModifyingPrefix = 'SELF_MOD';
    dasm.addOpcodeBytes      = false;
    dasm.opcodesLowerCase    = false;
    dasm.initLabels();
    dasm.memory.setMemory(0, BINARY);
    dasm.setLabel(0);
    return dasm;
}


suite('A10 — writeSymbolsOut', () => {

    let tmpDir: string;

    setup(() => {
        tmpDir = mkdtempSync(join(tmpdir(), 'z80-symbolsout-'));
    });


    // ------------------------------------------------------------------
    // getSymbolsData
    // ------------------------------------------------------------------

    suite('getSymbolsData', () => {

        test('returns SymbolEntry array after disassembly', function () {
            const dasm = makeDasm();
            dasm.disassemble();
            const symbols: SymbolEntry[] = dasm.getSymbolsData();
            assert.ok(Array.isArray(symbols), 'must return an array');
            assert.ok(symbols.length >= 2, 'must have at least two subroutines');
        });

        test('entries are sorted by address', function () {
            const dasm = makeDasm();
            dasm.disassemble();
            const symbols: SymbolEntry[] = dasm.getSymbolsData();
            for (let i = 1; i < symbols.length; i++)
                assert.ok(symbols[i].addr > symbols[i - 1].addr, 'addresses must be ascending');
        });

        test('subroutine entries have isSub=true', function () {
            const dasm = makeDasm();
            dasm.disassemble();
            const symbols: SymbolEntry[] = dasm.getSymbolsData();
            const subs = symbols.filter(s => s.isSub);
            assert.ok(subs.length >= 2, 'both subroutines must have isSub=true');
        });

        test('all returned entries have a name', function () {
            const dasm = makeDasm();
            dasm.disassemble();
            const symbols: SymbolEntry[] = dasm.getSymbolsData();
            for (const s of symbols)
                assert.ok(s.name && s.name.length > 0, `entry at ${s.addr.toString(16)} must have a name`);
        });
    });


    // ------------------------------------------------------------------
    // writeSymbolsOut — file content
    // ------------------------------------------------------------------

    suite('writeSymbolsOut', () => {

        function runAndRead(): string {
            const dasm = makeDasm();
            dasm.disassemble();
            const outPath = join(tmpDir, 'out.sym');
            writeSymbolsOut(outPath, dasm.getSymbolsData());
            return readFileSync(outPath, 'utf8');
        }

        test('output contains the auto-generated header', () => {
            const content = runAndRead();
            assert.ok(content.includes('Auto-generated by z80map --symbolsout'),
                'header line must be present');
        });

        test('subroutine entries have structured-field placeholders', () => {
            const content = runAndRead();
            assert.ok(content.includes('; summary: —'), 'summary placeholder must appear');
            assert.ok(content.includes('; action: —'),  'action placeholder must appear');
            assert.ok(content.includes('; entry: —'),   'entry placeholder must appear');
            assert.ok(content.includes('; exit-success: —'), 'exit-success placeholder must appear');
            assert.ok(content.includes('; exit-failure: —'), 'exit-failure placeholder must appear');
        });

        test('address lines use uppercase hex with no trailing comment', () => {
            const content = runAndRead();
            // Each named label must produce a line "XXXX name" with no "; ..." suffix.
            const addrLines = content.split('\n').filter(l => /^[0-9A-F]{4} \w/.test(l));
            assert.ok(addrLines.length >= 2, 'at least two address lines expected');
            for (const l of addrLines)
                assert.ok(!l.includes(';'), `address line must not contain a comment: ${l}`);
        });

        test('no prose auto-comment lines (Size=, CC=, etc.)', () => {
            const content = runAndRead();
            assert.ok(!content.includes('Size='), 'prose statistics must not appear');
            assert.ok(!content.includes('CC='),   'cyclomatic-complexity stats must not appear');
        });

        test('entries appear in address order', () => {
            const content = runAndRead();
            const addrLines = content.split('\n')
                .filter(l => /^[0-9A-F]{4} \w/.test(l))
                .map(l => parseInt(l.slice(0, 4), 16));
            for (let i = 1; i < addrLines.length; i++)
                assert.ok(addrLines[i] > addrLines[i - 1], 'entries must be in address order');
        });
    });


    // ------------------------------------------------------------------
    // writeSymbolsOut — edge cases
    // ------------------------------------------------------------------

    suite('writeSymbolsOut edge cases', () => {

        test('empty symbol list produces header-only file', () => {
            const outPath = join(tmpDir, 'empty.sym');
            writeSymbolsOut(outPath, []);
            const content = readFileSync(outPath, 'utf8');
            assert.ok(content.includes('Auto-generated'), 'header must still appear');
            const addrLines = content.split('\n').filter(l => /^[0-9A-F]{4}/.test(l));
            assert.strictEqual(addrLines.length, 0, 'no address lines for empty list');
        });

        test('data label entry has no placeholder block', () => {
            const outPath = join(tmpDir, 'data.sym');
            const symbols: SymbolEntry[] = [
                { addr: 0x1234, name: 'MY_DATA', isSub: false },
            ];
            writeSymbolsOut(outPath, symbols);
            const content = readFileSync(outPath, 'utf8');
            assert.ok(!content.includes('; summary:'), 'data label must not get placeholders');
            assert.ok(content.includes('1234 MY_DATA'), 'address line must be present');
        });

        test('subroutine entry gets placeholders immediately before address line', () => {
            const outPath = join(tmpDir, 'sub.sym');
            const symbols: SymbolEntry[] = [
                { addr: 0xBB00, name: 'KL_CHOKE_OFF', isSub: true },
            ];
            writeSymbolsOut(outPath, symbols);
            const lines = readFileSync(outPath, 'utf8').split('\n');
            const addrIdx = lines.findIndex(l => l === 'BB00 KL_CHOKE_OFF');
            assert.ok(addrIdx > 0, 'address line must exist');
            assert.strictEqual(lines[addrIdx - 1], '; exit-failure: —',
                'exit-failure placeholder must immediately precede address line');
        });

        test('user-supplied (isFixed) labels are excluded from --symbolsout', () => {
            // Labels from --symbols input are marked isFixed. They must not
            // appear in --symbolsout so the output can be appended to the
            // --symbols file without creating duplicates.
            const dasm = makeDasm();
            dasm.setLabel(0x0000, 'MY_ENTRY');
            const lbl = dasm.labels.get(0x0000);
            lbl.isFixed = true;
            dasm.disassemble();
            const symbols: SymbolEntry[] = dasm.getSymbolsData();
            const found = symbols.find((s: SymbolEntry) => s.name === 'MY_ENTRY');
            assert.ok(!found, 'isFixed label must be excluded from getSymbolsData()');
        });
    });
});
