import {writeFileSync} from 'fs';


/** Describes a single discovered item from a CPC disassembly pass. */
export interface DiscoveredEntry {
	kind: 'codelabel' | 'datalabel' | 'datarange';
	addr: number;
	name?: string;
	length?: number;	// only for datarange
}


/**
 * Writes discovered labels and data ranges to a plain-text args file.
 * The output can be reviewed and then re-used as input to --args.
 * @param path    Output file path.
 * @param entries Array of discovered entries from the disassembly.
 */
export function writeArgsOut(path: string, entries: DiscoveredEntry[]): void {
	const lines = new Array<string>();

	lines.push('; Auto-generated by z80dismblr --cpc');
	lines.push('; Review before re-using as --args input');

	const kinds: Array<DiscoveredEntry['kind']> = ['codelabel', 'datalabel', 'datarange'];

	for (const kind of kinds) {
		const group = entries.filter(e => e.kind === kind);
		if (group.length === 0)
			continue;

		lines.push('');
		lines.push('; --- ' + kind + ' entries ---');

		for (const entry of group) {
			lines.push('');
			lines.push('--' + kind);
			lines.push('0x' + entry.addr.toString(16).toUpperCase().padStart(4, '0'));
			if (entry.name !== undefined)
				lines.push(entry.name);
			if (entry.length !== undefined)
				lines.push(String(entry.length));
		}
	}

	writeFileSync(path, lines.join('\n') + '\n');
}
