import {writeFileSync} from 'fs';


/**
 * A single named label entry for the --symbolsout file.
 * Only labels that have a name are included; nameless addresses are filtered
 * out before this point.
 */
export interface SymbolEntry {
	addr:  number;
	name:  string;
	isSub: boolean;   // true for CODE_SUB / CODE_RST — gets structured-field placeholders
}


/** Describes a single discovered item from a CPC disassembly pass. */
export interface DiscoveredEntry {
	kind: 'codelabel' | 'datalabel' | 'datarange';
	addr: number;
	name?: string;
	length?: number;	// only for datarange
}


/**
 * Writes a merged args file: all input args (one option+params per line) followed by
 * auto-discovered dataranges. The file can be used directly as --args input on the next run.
 * @param path        Output file path.
 * @param stableArgs  Input args captured during this run (one formatted string per option).
 * @param discovered  Auto-discovered entries (only datarange entries are written here).
 */
export function writeArgsOut(path: string, stableArgs: string[], discovered: DiscoveredEntry[]): void {
	const lines = new Array<string>();

	lines.push('# Auto-generated by z80dismblr --argsout');
	lines.push('# Review before re-using as --args input');

	// Write all input args, one option per line
	if (stableArgs.length > 0) {
		lines.push('');
		lines.push('# --- input args ---');
		for (const a of stableArgs)
			lines.push(a);
	}

	// Append auto-discovered dataranges
	const dataRanges = discovered.filter(e => e.kind === 'datarange');
	if (dataRanges.length > 0) {
		lines.push('');
		lines.push('# --- auto-discovered dataranges ---');
		for (const entry of dataRanges) {
			const addrStr = '0x' + entry.addr.toString(16).toUpperCase().padStart(4, '0');
			lines.push('--datarange ' + addrStr + ' ' + entry.length);
		}
	}

	writeFileSync(path, lines.join('\n') + '\n');
}


/** Structured-field placeholder block emitted for every subroutine entry. */
const SUB_PLACEHOLDERS = [
	'; summary: —',
	'; action: —',
	'; entry: —',
	'; exit-success: —',
	'; exit-failure: —',
];


/**
 * Writes a skeleton symbol file from all named labels discovered during
 * disassembly. Only named entries are emitted; nameless addresses and all
 * prose/auto-generated comment text are omitted.
 *
 * @param path     Output file path.
 * @param symbols  Named label entries, sorted by address.
 * @param ports    Optional port-label data from `Disassembler.getPortSymbolsData()`.
 *                 When provided, a `; --- discovered I/O ports ---` section is
 *                 appended at the end of the file.
 */
export function writeSymbolsOut(
	path:    string,
	symbols: SymbolEntry[],
	ports?:  {named: Array<{spec: string; name: string}>; unnamed: number[]},
): void {
	const lines = new Array<string>();

	lines.push('; Auto-generated by z80dismblr --symbolsout');
	lines.push('; Review and complete, then use as --symbols input.');

	for (const entry of symbols) {
		lines.push('');
		if (entry.isSub)
			lines.push(...SUB_PLACEHOLDERS);
		const addrStr = entry.addr.toString(16).toUpperCase().padStart(4, '0');
		lines.push(addrStr + ' ' + entry.name);
	}

	// I/O port section — only when port data was supplied and is non-empty.
	if (ports && (ports.named.length > 0 || ports.unnamed.length > 0)) {
		lines.push('');
		lines.push('; --- discovered I/O ports ---');

		for (const {spec, name} of ports.named)
			lines.push('port:' + spec + '   ' + name);

		for (const port of ports.unnamed) {
			const hex = port.toString(16).toUpperCase().padStart(4, '0');
			lines.push('; port:' + hex + '   PORT_' + hex + '   ; accessed but unnamed — add a label and uncomment');
		}
	}

	writeFileSync(path, lines.join('\n') + '\n');
}
