import {writeFileSync} from 'fs';


/**
 * A single address entry for the --commentsout file, decoupled from internal
 * DisLabel / Comment types.
 */
export interface CommentEntry {
	addr: number;
	name?: string;
	linesBefore?: string[];
	inlineComment?: string;
	linesAfter?: string[];
}


/** Describes a single discovered item from a CPC disassembly pass. */
export interface DiscoveredEntry {
	kind: 'codelabel' | 'datalabel' | 'datarange';
	addr: number;
	name?: string;
	length?: number;	// only for datarange
}


/**
 * Writes discovered data ranges (and any codelabels) to a plain-text args file.
 * Labels are written to --commentsout instead. The output can be re-used as --args input.
 * @param path    Output file path.
 * @param entries Array of discovered entries from the disassembly.
 */
export function writeArgsOut(path: string, entries: DiscoveredEntry[]): void {
	const lines = new Array<string>();

	lines.push('; Auto-generated by z80dismblr --argsout');
	lines.push('; Review before re-using as --args input');

	const kinds: Array<DiscoveredEntry['kind']> = ['codelabel', 'datarange'];

	for (const kind of kinds) {
		const group = entries.filter(e => e.kind === kind);
		if (group.length === 0)
			continue;

		lines.push('');
		lines.push('; --- ' + kind + ' entries ---');

		for (const entry of group) {
			lines.push('');
			lines.push('--' + kind);
			lines.push('0x' + entry.addr.toString(16).toUpperCase().padStart(4, '0'));
			if (entry.name !== undefined)
				lines.push(entry.name);
			if (entry.length !== undefined)
				lines.push(String(entry.length));
		}
	}

	writeFileSync(path, lines.join('\n') + '\n');
}


/**
 * Writes the full set of labels and comments known after disassembly to a file
 * in --comments format. This includes entries loaded from --comments as well as
 * all labels generated during disassembly.
 * datarange entries cannot be expressed in comments format and are emitted as
 * commented-out --datarange hints at the end of the file.
 * @param path       Output file path.
 * @param comments   All label/comment entries from the disassembler, sorted by address.
 * @param dataRanges Discovered datarange entries to emit as hints.
 */
export function writeCommentsOut(path: string, comments: CommentEntry[], dataRanges: DiscoveredEntry[]): void {
	const lines = new Array<string>();

	lines.push('; Auto-generated by z80dismblr --commentsout');
	lines.push('; Review and use as --comments input');

	for (const entry of comments) {
		if (entry.linesBefore)
			for (const l of entry.linesBefore)
				lines.push(l);
		const addrStr = entry.addr.toString(16).toUpperCase().padStart(4, '0');
		const namePart = entry.name !== undefined ? ' ' + entry.name : '';
		const inlinePart = entry.inlineComment !== undefined ? ' ' + entry.inlineComment : '';
		lines.push(addrStr + namePart + inlinePart);
		if (entry.linesAfter)
			for (const l of entry.linesAfter)
				lines.push(l);
		lines.push('');	// blank line terminates each entry
	}

	// datarange entries have no equivalent in comments format — emit as reminders
	if (dataRanges.length > 0) {
		lines.push('');
		lines.push('; --- discovered datarange entries (not expressible in comments format) ---');
		lines.push('; Add these to your --args file:');
		for (const entry of dataRanges) {
			const addrStr = '0x' + entry.addr.toString(16).toUpperCase().padStart(4, '0');
			lines.push('; --datarange ' + addrStr + ' ' + entry.length);
		}
	}

	writeFileSync(path, lines.join('\n') + '\n');
}
